### ISSUE TITLE
Can nonce in CTR be just "unique", not random?

### ISSUE THREAD

**Issue by miki725** [oconnor663/applied_crypto_2021_fall#1]
https://github.com/oconnor663/applied_crypto_2021_fall/blob/dd75afb9a8abaa36555f9efc8ce2222469546203/pset3/readme.md#L424-L425

I thought in class we discussed that even in CTR mode, the nonce component (first 12 bytes) need to be completely random. Otherwise if it does not contain random bits the random "stream" will not be very random therefore breaking CTR completely.

Maybe the "unique" word is confusing me in:

> Or is it sufficient for it to be unique, like the CTR mode nonce?

Is that just my bad English over-reading this? Maybe clarify that a bit?

**Comment by miki725** [comment]
unless of course you meant "unique" nonce from `nacl.SecretBox`

**Comment by oconnor663** [comment]
CTR mode and secretbox have the same requirement for their nonces: they must be unique, but they don't necessarily have to be random. In the case of secretbox, making them random is often the most _practical_ way to ensure that they're unique, but in the case of AES-CTR, the nonce parameter is smaller and random nonces are risky.

> Otherwise if it does not contain random bits the random "stream" will not be very random therefore breaking CTR completely.

The AES-CTR stream will be indistinguishable from random as long as we never use the exact same AES inputs twice. We assume we're using the same key for many messages, so that part's not going to vary. The 16-byte input block is broken up into two parts, the (typically) 12 byte nonce and the (typically) 4 byte counter. We change the counter for every block, so as long as we don't overflow it, then no two blocks within the same message will ever use the same input. What remains is that we need to make sure that each nonce is only used with one message. If we've got that taken care of, then we'll never use the exact same set of AES inputs twice, and our nonce doesn't actually need to be random. (In a sense, AES is taking that "distinct but not very random looking" nonce and mixing it up into a "very random looking" output.) Does that make sense?

**Comment by oconnor663** [comment]
For what it's worth, I notice that you finished pset3 extremely quickly. Well done there. If you feel like the course might not be challenging enough, I'd be happy to suggest other exercises or topics that you could do on your own :)

**Comment by miki725** [comment]
Yeah thanks for the explanation. Basically the combination of nonce+counter+key cannot repeat with AES-CTR mode and in turn AES will guarantee "random"-looking stream of bits.

As far as the assignment, just trying to stay ahead of heavy next week at work. But if you have any cool projects I would love to take a look in spare time. Love learning how these things actually work by practice.

p.s. never saw CTR mode before. Pretty cool how simple and yet effective it is. Cant wait to learn about GCM mode

p.p.s. cant wait for the "implement hash function" assignment. that sounds loads of fun.

p.p.p.s. are they are standard simple crypto/security tools out there we can re-implement in the class? in networking class we had to reimplement ping/traceroute which I really enjoyed. now have different level of appreciation to all the standard tools out there...

**Comment by oconnor663** [comment]
> Basically the combination of nonce+counter+key cannot repeat with AES-CTR mode and in turn AES will guarantee "random"-looking stream of bits.

Precisely.

> As far as the assignment, just trying to stay ahead of heavy next week at work. But if you have any cool projects I would love to take a look in spare time. Love learning how these things actually work by practice.

If you'd like a big collection of medium-to-hard crypto exercises, I may have mentioned this one before: https://cryptopals.com/

If you like learning new programming languages, I'm a huge fan of the Rust, and a lot of modern crypto libraries are starting to be written in it. I'd be thrilled to suggest materials you could start out with if you wanted to learn Rust. I think it's especially interesting to [compare Rust and C++](https://www.youtube.com/watch?v=IPmRDS0OSxM), if you know one or both.

Also by the way, if you know any other students in the "experienced programmers looking for more challenging problems" boat, please do let me know. It's hard to get to know the class over Zoom.

> p.s. never saw CTR mode before. Pretty cool how simple and yet effective it is. Cant wait to learn about GCM mode

Surprisingly simple, right?!

Another very interesting advantage of something like CTR mode, is actually the fact that the plaintext never passes through the cipher. Why is that an advantage? Because it rules out a certain class of attacks: As an attacker, I might be interested in creating/discovering some pathological plaintext that exploits the inner structure of the cipher in some way, so that the cipher output leaks more information about the key than it should. (There are tons of practical scenarios where an attacker might be able to choose the plaintext that the victim encrypts. For example if I want to attack Twitter like this, I could just put my special plaintext in a tweet, and then Twitter would encrypt it for me when I loaded twitter.com over HTTPS.) But because stream ciphers like AES-CTR don't pass attacker-controlled plaintext through the block cipher, the attack surface is smaller.

Now in the case of AES, it's designed to be a secure block cipher, so it has to "pay the cost" of doing all the mixing necessary to resist any attack like this. But stream ciphers that are designed to be stream ciphers from the very beginning can avoid paying this cost. D.J. Bernstein, the inventor of Salsa and ChaCha, makes this point in section 3.2 of the [original Salsa paper](https://cr.yp.to/snuffle/salsafamily-20071225.pdf).

> p.p.s. cant wait for the "implement hash function" assignment. that sounds loads of fun.

I got my own implementation of the "length extension attack" working just today. I think you're gonna love it :)

> p.p.p.s. are they are standard simple crypto/security tools out there we can re-implement in the class?

Hmm, I'll think about this. I've certainly considered having us reimplement secretbox once we've learned about all its components. (And we did just learn about XSalsa20. Poly1305 will come in Chapter 8 I think.) But in terms of actual standalone software, I don't have any greate ideas. Real world crypto apps like web browsers, or OpenPGP, or bitcoin clients, tend to be quite complex. But maybe we could implement pieces of what bitcoin does, for example verifying the hash of a black? I'll think more about this, but let me know if you have any ideas.

**Comment by miki725** [comment]
> I got my own implementation of the "length extension attack" working just today. I think you're gonna love it :)

For the record the sha2 project is amazing! It breaks everything super well. Thank you for guiding it very well as well. At least conceptually on high level how sha2 works makes sense now. Whats quite amazing is how simple all the operations are. Like just some basic math and boolean algebra. And it totally scrambles everything!

p.s. The algorithm details of `message_schedule` and `round` are a mystery though. Like why in `round` `temp*` vars are only used in final `state[0]` and `state[4]` positions? Why not different positions? Why `temp*` calculation itself uses specific state indexes? I guess that's part of the hash function design itself. Hopefully can make one of the office hours to chat more about how these things are designed.

**Comment by oconnor663** [comment]
Good lord man. Please tell me it at least took you a couple hours 😅

> The algorithm details of message_schedule and round are a mystery though.

Honestly I don't know most of the answers here. Sometimes there's trial and error involved, where you consider a few different designs, try a bunch of known attacks on all of them, and then just pick whichever one seems to be most resistant to those attacks. It might not always be clear *why* it's better at the time. Section 7.4 of the BLAKE3 paper is an example of this. (Samuel Neves is the expert in area and wrote that section.)

In other cases, sometimes you do certain things because they perform well in hardware or with certain instruction sets. SHA-2 was definitely designed with hardware in mind. But again, I'm not a hardware guy, so I don't have a ton of insight here. Hopefully we'll get a guest lecture from John Viega later in the semester, and he might be able to answer some of these questions.
